[CmdletBinding()]
param(
    [switch]$Apply,
    [string[]]$Root = @("src", "tests")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$targetRoots = foreach ($entry in $Root) {
    if ([System.IO.Path]::IsPathRooted($entry)) {
        $entry
    }
    else {
        Join-Path $repoRoot $entry
    }
}

foreach ($targetRoot in $targetRoots) {
    if (-not (Test-Path $targetRoot)) {
        throw "Target root '$targetRoot' does not exist."
    }
}

$copyrightLine = "// SPDX-FileCopyrightText: 2025–2026 Власов Виталий Андреевич <vital.cc55@gmail.com>"
$spdxLine = "// SPDX-License-Identifier: AGPL-3.0-or-later"
$expectedHeader = "$copyrightLine`r`n$spdxLine"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Get-NormalizedContent {
    param(
        [string]$Content
    )

    $text = $Content -replace "^\uFEFF", ""
    $text = $text -replace "^(// SPDX-FileCopyrightText: .*\r?\n|// Copyright .*\r?\n)?(// SPDX-License-Identifier: .*\r?\n)?(\r?\n)?", ""
    return $text
}

function Convert-ToCanonicalNewlines {
    param(
        [string]$Content
    )

    return (($Content -replace "^\uFEFF", "") -replace "\r?\n", "`r`n").TrimEnd("`r", "`n")
}

$files = @(
    foreach ($targetRoot in $targetRoots) {
        Get-ChildItem $targetRoot -Recurse -Filter *.cs |
            Where-Object {
                $_.FullName -notmatch '\\obj\\|\\bin\\'
            }
    }
) | Sort-Object FullName -Unique

$missing = New-Object System.Collections.Generic.List[string]
$updated = New-Object System.Collections.Generic.List[string]
$skippedGenerated = New-Object System.Collections.Generic.List[string]

foreach ($file in $files) {
    $content = [System.IO.File]::ReadAllText($file.FullName)
    if ($content -match '^\s*//\s*<auto-generated>') {
        $skippedGenerated.Add($file.FullName)
        continue
    }

    $normalized = Get-NormalizedContent -Content $content
    $expectedContent = "$expectedHeader`r`n`r`n$normalized"

    $alreadyCorrect = (Convert-ToCanonicalNewlines -Content $content) -eq (Convert-ToCanonicalNewlines -Content $expectedContent)

    if ($alreadyCorrect) {
        continue
    }

    if ($Apply) {
        [System.IO.File]::WriteAllText($file.FullName, $expectedContent, $utf8NoBom)
        $updated.Add($file.FullName)
    }
    else {
        $missing.Add($file.FullName)
    }
}

if ($Apply) {
    Write-Output "UPDATED=$($updated.Count)"
    foreach ($path in $updated) {
        Write-Output $path
    }
    if ($skippedGenerated.Count -gt 0) {
        Write-Output "SKIPPED_GENERATED=$($skippedGenerated.Count)"
    }
    exit 0
}

if ($missing.Count -gt 0) {
    Write-Output "MISSING=$($missing.Count)"
    foreach ($path in $missing) {
        Write-Output $path
    }
    if ($skippedGenerated.Count -gt 0) {
        Write-Output "SKIPPED_GENERATED=$($skippedGenerated.Count)"
    }
    exit 1
}

Write-Output "OK=0"
if ($skippedGenerated.Count -gt 0) {
    Write-Output "SKIPPED_GENERATED=$($skippedGenerated.Count)"
}
